# Generated by Django 6.0.5 on 2026-05-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('can_edit_all_recipes', 'Может редактировать любые рецепты'), ('can_delete_all_recipes', 'Может удалять любые рецепты')], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
